env:
  DOCKER_IMAGE: "inclusivedesign/node-browsers"

agent_tags: &agent_tags
  agents:
    name: "${BUILDKITE_AGENT_NAME?}"

steps:
  - name: "Build"
    command:
      - "docker build -t ${DOCKER_IMAGE} ."
    timeout_in_minutes: 15
    <<: *agent_tags

  - name: "Publish"
    command:
      - "docker push ${DOCKER_IMAGE}"
    branches: "master" # Do not push builds from PRs or other branches
    timeout_in_minutes: 5
    <<: *agent_tags

  - name: "Cleanup"
    command:
      - "docker image rm --force ${DOCKER_IMAGE}"
    timeout_in_minutes: 1
    <<: *agent_tags
