env:
  DOCKER_IMAGE: inclusivedesign/node-browsers

agent_tags: &agent_tags
  agents:
    name: "${BUILDKITE_AGENT_META_DATA_NAME?}"

steps:
  - name: "Build"
    command:
      - "docker build -t ${DOCKER_IMAGE}:${BUILDKITE_COMMIT} ."
    timeout_in_minutes: 10
    <<: *agent_tags

  - wait

  - name: "Test"
    command:
      - "docker run --rm -ti ${DOCKER_IMAGE}:${BUILDKITE_COMMIT} bash -c '/usr/bin/rpm -q firefox google-chrome-stable nodejs && grunt --version && testem --version && istanbul help'"
    timeout_in_minutes: 1
    <<: *agent_tags

  - wait

  - name: "Publish"
    command: "docker push ${DOCKER_IMAGE}:${BUILDKITE_COMMIT}"
    timeout_in_minutes: 5
    <<: *agent_tags

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command: "docker image rm --force ${DOCKER_IMAGE}:${BUILDKITE_COMMIT}"
    timeout_in_minutes: 1
    <<: *agent_tags
