steps:
  - block: "Release!"
    fields:
      - text: "Docker Image Name"
        key: "image-name"
        default: "${IMAGE_NAME}"
        required: true

      - text: "Image Source Tag"
        key: "source-tag"
        default: "${SOURCE_TAG}"
        required: true

      - text: "Image Target Tag"
        key: "target-tag"
        default: "latest"
        required: true

  - name: ":rocket:"
    command:
      - "./release/release.sh"
    concurrency: 1
    concurrency_group: "docker-release"
